import Head from 'next/head'
import  {getHomepagePhotos} from "@/sanity/sanity-utils"
import { homepagePhotosType } from '@/types/Project-type'
import Pic from '@/components/Pic/Pic'

 



export default function Home(props: {homePhotos:homepagePhotosType[]}) {

const data = props.homePhotos
const randomIndex = Math.floor(Math.random() * data[0].images.length)

console.log(data)


  return (
 
    
      <><Head>
      <title>Test Roman Sanity</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
   <div>
    <Pic  src={data[0].images[randomIndex].image} width={data[0].images[randomIndex].width} height={data[0].images[randomIndex].height} alt={data[0].name} />  


   </div>
    </>
        
  )
}


export async function getStaticProps() {
  const photos = await getHomepagePhotos();

  if (!photos || Object.keys(photos).length === 0) {
    return { notFound: true };
  }

  const photosArray = Object.values(photos);
  console.log('photos', photos);
  

  return {
    props: { homePhotos: photosArray },
    revalidate: 30
  };
}
